# Generated by Django 4.0.4 on 2023-04-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('original_file', models.ImageField(upload_to='images/original/')),
                ('thumbnail_file', models.ImageField(upload_to='images/thumbnail/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
